name       : gspell
version    : 1.12.1
release    : 24
source     :
    - https://download.gnome.org/sources/gspell/1.12/gspell-1.12.1.tar.xz : 8ec44f32052e896fcdd4926eb814a326e39a5047e251eec7b9056fbd9444b0f1
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-i18n)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
