name       : gspell
version    : 1.2.2
release    : 4
source     :
    - https://download.gnome.org/sources/gspell/1.2/gspell-1.2.2.tar.xz : d93c677b77e8b92cf00693ade6ea0d46e478fc5fe75cc508111428e77e90661e
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(enchant)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
