name       : gspell
version    : 1.6.0
release    : 7
source     :
    - https://download.gnome.org/sources/gspell/1.6/gspell-1.6.0.tar.xz : b5d73dab4bda45cde4bdeed04e472dca8a3e16ea19739cfb66237553e91f872d
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
