name       : gspell
version    : 1.11.1
release    : 21
source     :
    - https://download.gnome.org/sources/gspell/1.11/gspell-1.11.1.tar.xz : ef6aa4e3f711775158a7e241a5f809cf2426bc0e02c23a7d2b5c71fc3de00292
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icu-i18n)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
