name       : gspell
version    : 1.4.0
release    : 5
source     :
    - https://download.gnome.org/sources/gspell/1.4/gspell-1.4.0.tar.xz : 8d317c6bf6ae298b0a6c89aed63bc133c85c8ce7e8e799d870da560ad10b2d4e
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
