name       : gspell
version    : 1.0.3
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gspell/1.0/gspell-1.0.3.tar.xz : d95905e6c631e34911e8e3feeb364815bf3fd7ccd1dac118a34bcbae70261bd5
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(enchant)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
