name       : gspell
version    : 1.6.1
release    : 9
source     :
    - https://download.gnome.org/sources/gspell/1.6/gspell-1.6.1.tar.xz : f4d329348775374eec18158f8dcbbacf76f85be5ce002a92d93054ece70ec4de
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
