name       : gspell
version    : 1.4.1
release    : 6
source     :
    - https://download.gnome.org/sources/gspell/1.4/gspell-1.4.1.tar.xz : 442f88fecd7f9e00a6a9d0af2d762744dd3c119217ff11d6739500f75b0f10be
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
