name       : gspell
version    : 1.2.1
release    : 3
source     :
    - https://download.gnome.org/sources/gspell/1.2/gspell-1.2.1.tar.xz : 9f1c3e5f09693a786e8b8dfdc5f142e9c9641d8674ec687014be928073d3f1a3
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : GTK+ Spell Checker Library
description: |
    GTK+ Spell Checker Library
builddeps  :
    - pkgconfig(gobject-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(enchant)
    - autoconf-archive
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
